project:
  type: website                 # manuscript-as-website
  output-dir: _site             # what GitHub Pages will serve

website:
  title: "Efficient and Scalable Posterior Surrogate for Seismic Inversion via Wavelet Score-Based Generative Models"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: abstract.qmd
        text: Paper
    right:
      - icon: github
        href: https://github.com/egesamuray/tunaAbi
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    fig-cap-location: bottom
    link-external-newwindow: true
  pdf:                          # optional—keeps your LaTeX template
    template-partials:
      - IMAGEAbstractTemplate.latex
