project:
  type: website
  output-dir: _site

website:
  title: "Efficient and scalable posterior surrogate for seismic inversion via wavelet score-based generative models"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: abstract.qmd
        text: Paper
    right:
      - icon: github
        href: https://github.com/slimgroup/IMAGE2025
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    fig-cap-location: bottom
    crossref:
      fig-title: "Figure"
      fig-prefix: "Figure"
    citations-hover: true
    footnotes-hover: true
    link-external-newwindow: true
  pdf:
    documentclass: article
    classoption: [onecolumn, 11pt]
    keep-tex: true
    toc: false
    include-in-header: 
      - \usepackage{amsmath}
      - \usepackage{booktabs}
      - \usepackage{hyperref}
